[package]
name = "llamalogs"
version = "0.1.0"
authors = ["Damien Stanton <damien.stanton@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
async-std = "1" 
futures = "0.3"
surf = "1.0"
thiserror = "1.0"